spring.datasource.url=jdbc:postgresql://localhost:5432/campus_emergency
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySecretKey
jwt.expiration=86400000

expo.push.url=https://exp.host/--/api/v2/push/send

server.port=8080